server:
  port: 8080        # 443
spring:
  data:
    redis:
      host: 124.222.33.49
      port: 6379
      password: myredis123
      database: 0
    mongodb:
      uri: mongodb://myadmin:myadmin123@124.222.33.49:27017/myapp?authSource=admin&authMechanism=SCRAM-SHA-256
      username: myadmin
      password: myadmin123
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://124.222.33.49:3306/programbook?characterEncoding=utf-8&useSSL=false&autoReconnect=true&verifyServerCertificate=false
    username: root
    password: root123
    hikari:
      connection-test-query: SELECT 1 FROM DUAL
      connection-timeout: 36000
      maximum-pool-size: 500
      max-lifetime: 600000
      minimum-idle: 20
      validation-timeout: 3000
      idle-timeout: 60000
      connection-init-sql: SET NAMES utf8mb4
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
logging:
  level:
    com:
      baomidou:
        mybatisplus: debug
      book:
        mapper: debug